defaults:
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: default

paginate: 10
paginate_path: "/blog/page:num/"

title: Arghavan Edalat
subtitle: Master's student in Data Science

# left_side:
#   background_image: https://www.american.edu/spa/data-science/images/datascience-hero.jpg
#   background_color: "#B0C4DE"
#   close_button_color: "#F00"
#   text_color: "#F00"


# Side Menu Links
menu:
  - text: Portfolio
    link: /
    icon: ""

  - text: Skills & Offers
    link: /skills-and-offers
    icon: ""

  - text: Contact Me
    link: /contact
    icon: ""

  - text: My CV
    link: /resume
    icon: ""

  - text: Blog Posts
    link: /blog
    icon: ""

# Socialmedia Icons
social_icons:
  - name: linkedin
    link: https://www.linkedin.com/arghavanedalat
    icon: fab fa-linkedin

  - name: github
    link: https://github.com/arghavanedalat
    icon: fab fa-github-square



    
