defaults:
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: default

paginate: 10
paginate_path: "/blog/page:num/"

title: Arghavan Edalat
subtitle: Master's student in Data Science

left_side:
  background_image: "https://img.freepik.com/free-photo/vertical-shot-beautiful-starry-sky_181624-25916.jpg?w=360"
  text_color: "#FFFFFF"


# Side Menu Links
menu:
  - text: Portfolio
    link: /
    icon: ""

  - text: My CV
    link: /resume
    icon: ""

# Socialmedia Icons
social_icons:
  - name: linkedin
    link: https://www.linkedin.com/arghavanedalat
    icon: fab fa-linkedin

  - name: github
    link: https://github.com/arghavanedalat
    icon: fab fa-github-square



    
